# This is a basic workflow to help you get started with Actions

name: deploy-book

# Updates public documentation for new releases.
on:
  release:
    types: [published]

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter book build ./docs
    
    - name: Upload book
      uses: actions/upload-artifact@v4
      with:
        name: html-pages
        path: ./_build/html

  # Push the book's HTML to github-pages
  deploy-book:
    needs: build-book
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: html-pages
          path: ./_build/html
          
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
